```{r data{{thisTaxa}}}

  summariseTaxa <- "{{thisTaxa}}"

  thisTaxaMods <- taxaMods %>%
    dplyr::mutate(thisTaxa = gsub(" ","",Taxa)) %>%
    dplyr::filter(thisTaxa == summariseTaxa) %>%
    dplyr::mutate(modLoop = paste0(thisTaxa,gsub(" ","",type)))

  taxa <- thisTaxaMods$Taxa[[1]]

  common <- thisTaxaMods$Common[[1]]
  
```

## _`r taxa`_: `r common`

```{r taxaModelPrep{{thisTaxa}}, include=FALSE}

  taxaModel = NULL

  for (i in thisTaxaMods$modLoop) {
    
    thisMod <- i
    
    taxaModel = c(taxaModel, knit_expand('child/taxaModel.Rmd'))
    
  }

```

`r paste(knit(text = taxaModel), collapse = '\n')`

### Overall

```{r dataOverall{{thisTaxa}}}

  taxaDat <- taxaModsOverall %>%
    dplyr::mutate(thisTaxa = gsub(" ","",Taxa)) %>%
    dplyr::filter(thisTaxa == summariseTaxa)

```

`r taxaDat$overall[[1]]$yearDiffText`. (Figure \@ref(fig:overallYearEffectPlot{{thisTaxa}})).

<br>

```{r overallYearEffectPlot{{thisTaxa}}, fig.width = 7, fig.cap = paste0("Overall effect of year on _",taxa,"_")}
  
  taxaDat$overall[[1]]$yearDiffOverallPlot

```